/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsFortuneWheelRouteImport } from './routes/projects.fortune-wheel'
import { Route as ProjectsAlprRouteImport } from './routes/projects.alpr'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsFortuneWheelRoute = ProjectsFortuneWheelRouteImport.update({
  id: '/projects/fortune-wheel',
  path: '/projects/fortune-wheel',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsAlprRoute = ProjectsAlprRouteImport.update({
  id: '/projects/alpr',
  path: '/projects/alpr',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/alpr': typeof ProjectsAlprRoute
  '/projects/fortune-wheel': typeof ProjectsFortuneWheelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/alpr': typeof ProjectsAlprRoute
  '/projects/fortune-wheel': typeof ProjectsFortuneWheelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/alpr': typeof ProjectsAlprRoute
  '/projects/fortune-wheel': typeof ProjectsFortuneWheelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/projects/$slug' | '/projects/alpr' | '/projects/fortune-wheel'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects/$slug' | '/projects/alpr' | '/projects/fortune-wheel'
  id:
    | '__root__'
    | '/'
    | '/projects/$slug'
    | '/projects/alpr'
    | '/projects/fortune-wheel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsAlprRoute: typeof ProjectsAlprRoute
  ProjectsFortuneWheelRoute: typeof ProjectsFortuneWheelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/fortune-wheel': {
      id: '/projects/fortune-wheel'
      path: '/projects/fortune-wheel'
      fullPath: '/projects/fortune-wheel'
      preLoaderRoute: typeof ProjectsFortuneWheelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/alpr': {
      id: '/projects/alpr'
      path: '/projects/alpr'
      fullPath: '/projects/alpr'
      preLoaderRoute: typeof ProjectsAlprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsAlprRoute: ProjectsAlprRoute,
  ProjectsFortuneWheelRoute: ProjectsFortuneWheelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
